version: '3'

services:
  opensips:
    image: opensips:3.2.9
    container_name: my_opensips
    network_mode: host
    environment:
      PUBLIC_IP: ${PUBLIC_IP}
      PORT: ${PORT}
      DOLLOR: ${DOLLOR:-'$'}
    volumes:
      - "./:/usr/local/etc/opensips/"
